# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0613dc42008b6c26d26e085e133f36574be14da7ba47f1a08512883dba6135737668cbded482b2924268a27b3c057f9004f7d69913d43d351ee25ddda4fe2ee

test:
  secret_key_base: 9c2c6adb123e643d870453211ea8527f3ca57b1bd3a6a633a80a8f3b65cb221996fa561651f790f9e04f781e037259c2453a0ce1e5e86763223c9652f82b2519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
